import { Poppins, Unbounded, Urbanist } from "next/font/google";
import "@styles/globals.css";
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import Header from "./components/header";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "600"] });
const unbounded = Unbounded({ subsets: ["latin"], weight: ["400", "600"] });
const urbanist = Urbanist({ subsets: ["latin"], weight: ["400", "600"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Remove the Google Fonts link */}
      </head>
      <body className={`${poppins.className} ${unbounded.className} ${urbanist.className}`}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
